apps/startups/urls.py
from django.urls import path


from .views import (
    HomeView, startup_create, StartupUpdateView, StartupDeleteView,
    ReportListView, report_create, expense_create

)
app_name = "startups"
urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('startups/create/', startup_create, name="startup_create"),
    path('startups/<int:pk>/update/', StartupUpdateView.as_view(), name="startup_update"),
    path('startups/<int:pk>/delete/', StartupDeleteView.as_view(), name="startup_delete"),

    path('reports/<int:startup_id>/', ReportListView.as_view(), name="reports"),
    path('reports/<int:startup_id>/add-revenue/', report_create, name="revenue-add"),
    path('reports/<int:startup_id>/add-expense/', expense_create, name="expense-add"),
    
    
    path('admin/', HomeView.as_view(), name="admin")
]

config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('djadmin/', admin.site.urls),
    path('', include("apps.user.urls")),
    path('', include("apps.startups.urls")),
]

apps/startups/models.py
from django.db import models
from django.conf import settings
from apps.user.models import User
class BaseModel(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, 
                            on_delete=models.CASCADE, related_name="+")
    date_created = models.DateTimeField(auto_now=False, auto_now_add=True)

    
class Startups(BaseModel):
    name = models.CharField("Biznes nomi", max_length=150, unique=True)

    class Meta:
        verbose_name = "Startup"
        verbose_name_plural = "Startups"
        ordering = ("id", )
    def __str__(self):
        return self.name

    @property
    def get_revenues(self):
        return self.revenues.all()

    @property
    def curr_month_revenue(self):
        return self.get_revenues.last()


    @property
    def curr_month_outgoing(self):
        return self.outgoings.all().last()

    @property
    def all_users_revenues(self):
        if self.author.is_superuser:
            users = User.objects.all()
            revenues = []
            for user in users:
                try:
                    revenues.append(self.get_revenues.filter(startup=self, author=user).first().id)
                except:
                    pass
            return self.get_revenues.filter(id__in=revenues)
            
        return []
        

class Revenues(BaseModel):
    startup = models.ForeignKey("Startups", models.CASCADE, related_name="revenues")
    income = models.IntegerField("Joriy oyda olingan daromad", default=0)
    clients = models.IntegerField("Joriy oydagi mijozlar soni", default=0)

    is_rising = models.BooleanField(default=True)
    percentage = models.IntegerField("Process on Percentage", default=0)

    client_rising = models.BooleanField(default=True)
    client_percentage = models.IntegerField("Process on Percentage", default=0)
    
    class Meta:
        verbose_name = "Revenue"
        verbose_name_plural = "Revenues"
        ordering = ("-date_created", )

    def __str__(self):
        return str(self.id)

    @property
    def get_last_outgoing(self):
        res = self.startup.outgoings.filter(author=self.author).first()
        print("OUTGOING: ", res)
        return res

class Outgoings(BaseModel):
    startup = models.ForeignKey("Startups", models.CASCADE, related_name="outgoings")
    salary = models.IntegerField("Joriy oyda olingan daromad", default=0)
    marketing = models.IntegerField("Joriy oydagi mijozlar soni", default=0)

    is_rising = models.BooleanField(default=True)
    percentage = models.IntegerField("Process on Percentage", default=0)

    marketing_rising = models.BooleanField(default=True)
    marketing_percentage = models.IntegerField("Process on Percentage", default=0)

    class Meta:
        verbose_name = "Outgoing"
        verbose_name_plural = "Outgoings"
        ordering = ("-date_created", )

    def __str__(self):
        return f"{self.id} {self.salary} {self.marketing} {self.startup} {self.startup.author} {self.author}"

apps/startups/forms.py
from django import forms


from .models import Startups, Revenues


class StartupForm(forms.ModelForm):
    class Meta:
        model = Startups
        fields = ("name", )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['name'].widget.attrs['class'] = 'form-control'


class RevenueForm(forms.Form):

    income = forms.IntegerField()
    clients = forms.IntegerField()


class OutgoingForm(forms.Form):

    salary = forms.IntegerField()
    marketing = forms.IntegerField()

apps/startups/views.py
from django.shortcuts import render, redirect, get_list_or_404, get_object_or_404
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import Http404, HttpResponseForbidden
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, FormView, DetailView
from django.db.models import Q

from typing import Dict, Any
from .models import Revenues, Startups, Outgoings
from .forms import StartupForm, RevenueForm, OutgoingForm
from apps.user.models import User
# Create your views here.



class HomeView(LoginRequiredMixin, ListView):
    template_name = "startups/home.html"

    def get_queryset(self):
        queryset = Startups.objects.all()
        user = self.request.user
        if user.is_superuser:
            return queryset
        admins = User.objects.filter(is_superuser=True)
        return queryset.filter(Q(author=user) | Q(author__in=admins))

    def get_context_data(self, **kwargs):
        kwargs.setdefault("page_title", "Biznes Loyihalar")
        return super().get_context_data(**kwargs)

    def get(self, request, *args, **kwargs):
        if request.user.is_superuser:
            self.template_name = "startups/vc_index.html"
        return super().get(request, *args, **kwargs)

def startup_create(request):
    kwargs = {
        "page_title": "LOYIHA YARATISH",
        "action_name": "Jo'natish",
        "button_tag": "primary"
    }

    if request.method == "POST":
        form = StartupForm(request.POST)
        if form.is_valid():
            startup = form.save(commit=False)
            startup.author = request.user
            startup.save()

            return redirect("/")
    else:
        form = StartupForm()
    kwargs.setdefault("form", form)
    return render(request, "user/create_form.html", kwargs)

class StartupDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    template_name = "startups/detail.html"
    model = Startups

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        kwargs["categories"] = self.get_revenue_categories()
        return super().get_context_data(**kwargs)
    
    def get_revenue_categories(self):
        return get_list_or_404(Revenues, startup=self.get_object())


class StartupUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    template_name = "user/create_form.html"
    model = Startups
    form_class = StartupForm
    success_url = "/"

    def get_success_url(self) -> str:
        messages.add_message(self.request, messages.SUCCESS, "Muvaffaqiyatli yangilandi")
        # if self.request.user.is_superuser:
        #     self.success_url = "/admin/"
        return super().get_success_url()
    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        kwargs.update({
            "page_title": "LOYIHA TAHRIRLASH",
            "action_name": "Jo'natish",
            "button_tag": "primary"
        })
        return super().get_context_data(**kwargs)
    
    def test_func(self):
        return self.get_object().author == self.request.user


class StartupDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    template_name = "startups/delete_form.html"
    model = Startups
    success_url = "/"

    def get_success_url(self) -> str:
        messages.add_message(self.request, messages.SUCCESS, "Muvaffaqiyatli o'chirildi")
        # if self.request.user.is_superuser:
        #     self.success_url = "/admin/"
        return super().get_success_url()

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        kwargs.setdefault("page_title", "LOYIHANI O'CHIRISH")
        return super().get_context_data(**kwargs)

    def test_func(self):
        return self.get_object().author == self.request.user


class ReportListView(LoginRequiredMixin, ListView):
    template_name = "startups/report_detail.html"
    startup = None

    def get_queryset(self):
        queryset = Revenues.objects.all()
        kwargs = {"startup": self.startup}
        if not self.request.user.is_superuser:
            kwargs["author"] = self.request.user
        return queryset.filter(**kwargs).order_by("-date_created")

    def get(self, request, *args, **kwargs):
        self.startup = get_object_or_404(Startups, pk=kwargs["startup_id"])
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        
        kwargs = {"startup": self.startup}
        if not self.request.user.is_superuser:
            kwargs["author"] = self.request.user

        outgoings = Outgoings.objects.filter(**kwargs).order_by("-date_created")

        kwargs.update({
            "outgoings": outgoings,
            "startup": self.startup
        })
        return super().get_context_data(**kwargs)


def check_availability(request, startup_id: int):
    startup = get_object_or_404(Startups, pk=startup_id)
    if request.user.is_superuser:
        raise Http404
    if not request.user.is_superuser and startup.author != request.user and not startup.author.is_superuser:
        raise Http404
        # messages.add_message(request, messages.WARNING, "Sizga mumkinmas")
        # return redirect("startups:reports", startup_id=startup_id)


def report_create(request, startup_id: int):
    check_availability(request, startup_id)
    
    if request.method == "POST":
        form = RevenueForm(request.POST)
        if form.is_valid():
            income = form.cleaned_data.get("income")
            clients = form.cleaned_data.get("clients")

            last_revenue = Revenues.objects.filter(startup_id=startup_id, author=request.user).last() # filtered on -date_created
            
            revenue = Revenues(
                income=income, clients=clients, startup_id=startup_id, author=request.user
            )
            try:
                revenue.percentage = (income - last_revenue.income) / last_revenue.income * 100
            except:
                pass
            if revenue.percentage < 0:
                revenue.is_rising = False

            try:
                revenue.client_percentage = (clients- last_revenue.clients) / last_revenue.clients * 100
            except:
                pass
            if revenue.client_percentage < 0:
                revenue.client_rising = False
            revenue.save()
            return redirect("startups:reports", startup_id=startup_id)
    else:
        form = RevenueForm() 
    
    return render(request, "startups/revenue_add.html", {"form": form})


def expense_create(request, startup_id: int):
    check_availability(request, startup_id)
    if request.method == "POST":
        form = OutgoingForm(request.POST)
        if form.is_valid():
            salary = form.cleaned_data.get("salary")
            marketing = form.cleaned_data.get("marketing")

            last_expense = Outgoings.objects.filter(startup_id=startup_id, author=request.user).last() # filtered on -date_created
            
            expense = Outgoings(
                salary=salary, marketing=marketing, startup_id=startup_id, author=request.user
            )
            try:
                expense.percentage = (salary - last_expense.salary)/ last_expense.salary * 100 
            except:
                pass
            if expense.percentage < 0:
                expense.is_rising = False
            
            try:
                expense.marketing_percentage = (marketing - last_expense.marketing)/ last_expense.marketing * 100
            except:
                pass
            if expense.marketing_percentage < 0:
                expense.marketing_rising = False

            expense.save()
            return redirect("startups:reports", startup_id=startup_id)
    else:
        form = OutgoingForm() 
    
    return render(request, "startups/expense_add.html", {"form": form})

apps/startups/views/admin.py
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.http import HttpResponseNotFound

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib import messages

from django.views import View
from django.views.generic import UpdateView, DetailView, DeleteView

from apps.startups.views.startups import BaseObjectView
from ..models import Revenues, RevenueFields, Startups
from ..forms import RevenueForm, FieldForm


class AdminRevenueView(LoginRequiredMixin, UserPassesTestMixin, View):
    template_name = "startups/admin.html"
    model = Startups

    def get_queryset(self, ):
        return self.model.objects.all()

    def get(self, request, *args, **kwargs):
        context = dict()
        context["startups"] = self.get_queryset() 
        return render(request, self.template_name, context)
    


    def test_func(self):
        return self.request.user.is_superuser

apps/startups/views/revenues.py
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.http import HttpResponseNotFound

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib import messages

from django.views import View
from django.views.generic import UpdateView, DetailView, DeleteView

from apps.startups.views.startups import BaseObjectView
from ..models import Revenues, RevenueFields, Startups
from ..forms import RevenueForm, FieldForm, RevenueModelForm


class RevenueView(LoginRequiredMixin, View):
    model = Revenues
    template_name = "startups/_detail.html"
    form_class = RevenueForm

    def get(self, request, startup_id, *args, **kwargs):
        
        context = self.get_context_data(startup_id=startup_id)
        return render(request, self.template_name, context)
    
    def post(self, request, startup_id, *args, **kwargs):
        form = self.form_class(request.POST)
        context = self.get_context_data(startup_id=startup_id)

        if form.is_valid():
            form.save(startup=self.get_startup(startup_id), request=request)
        
        return render(request, self.template_name, context)

    def get_context_data(self, **kwargs):
        startup = self.get_startup(kwargs['startup_id'])

        revenues = startup.revenues.all()
        kwargs.setdefault("revenues", revenues)
        kwargs.setdefault("startup", startup)
        form = self.form_class()
        kwargs.setdefault("form", form)
        return kwargs

    def get_startup(self, startup_id: int):
        startup = get_object_or_404(Startups, pk=startup_id)

        if startup.created_by == self.request.user or self.request.user.is_superuser:
            return startup
        else:
            return HttpResponseNotFound("Bunday object mavjud emas")


class RevenueUpdateView(BaseObjectView, UpdateView):
    template_name = "startups/_create_form.html"
    success_url = "/"
    model = Revenues
    page_title = "Hisobotni Tahrirlash"
    action_name = "Tahrirlash"
    form_class = RevenueModelForm


class RevenueDeleteView(BaseObjectView, DeleteView):
    template_name = "startups/_delete_form.html"
    model = Revenues
    success_url = "/"
    page_title = "Hisobotni O'chirish"
    action_name = "O'chirish"


class RevenueFieldCreateView(LoginRequiredMixin, View):
    template_name = "startups/_create_form.html"
    model = RevenueFields
    form_class = FieldForm

    def get(self, request, revenue_id, *args, **kwargs):
        
        context = self.get_context_data(revenue_id=revenue_id)
        return render(request, self.template_name, context)
    
    def post(self, request, revenue_id, *args, **kwargs):
        form = self.form_class(request.POST)
        context = self.get_context_data(revenue_id=revenue_id)

        if form.is_valid():
            revenue = self.get_revenue(revenue_id)
            form.save(revenue=revenue, request=request)
            messages.add_message(request, messages.INFO, "Soha yaratildi")
            return redirect("startups:startup_detail", pk = revenue.startup.id)
        else:
            messages.add_message(request, messages.DANGER, "Soha qiymatlari bilan bog'liq muammo yuzaga keldi, tekshiring")
        return render(request, self.template_name, context)

    def get_context_data(self, **kwargs):
        context = dict()

        revenue = self.get_revenue(kwargs['revenue_id'])
        context['revenue'] = revenue
        context["page_title"] = "Hisobot sohasini yaratish"
        context['action_name'] = "Yaratish"
        context['form'] = self.form_class()

        return context
    
    def get_revenue(self, revenue_id: int):
        revenue = get_object_or_404(Revenues, pk=revenue_id)

        if revenue.created_by == self.request.user or self.request.user.is_superuser:
            return revenue
        return HttpResponseNotFound("Bunday object mavjud emas")

templates/startups/_create_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
    <h4>{{page_title}}</h4>
{% endblock %}

{% block content %}
    <form method="post">
        <fieldset>
            {% csrf_token %}
            {{ form|crispy }}
        </fieldset>
        <button class="btn btn-primary" type="submit">{{action_name}}</button>

    </form>
{% endblock %}

templates/startups/_delete_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
    <h4>{{page_title}}</h4>
{% endblock %}

{% block content %}
    <form method="post">
        <h4> Rostan ham o'chirishni xohlaysizmi?</h4>
        <fieldset>
            {% csrf_token %}
            {{ form|crispy }}
        </fieldset>
        <button class="btn btn-danger" type="submit">{{action_name}}</button>
        <a href="{% url 'startups:home' %}" class="btn btn-outline-primary">Ortga</a>

    </form>
{% endblock %}

templates/startups/_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    <h4>{{ page_title }}</h4>
{% endblock %}

{% block content %}
    <div class="container">
        <div>
            <div>
                <h4 class="p-2 m-2">{{startup.name}}</h4>
            </div>
            <a href="{% url 'startups:startup_update' startup.id %}" class="btn btn-primary">Tahrirlash</a>
            
        </div>
        <hr>
        <form action="{% url 'startups:revenues' startup.id %}" class="form-group" method="post">
            {% csrf_token %}
            {{ form|crispy}}
            <button class="btn btn-primary p-2 m-2" type="submit">Hisobot yaratish</button>
        </form>
        {% for revenue in revenues %}
        <hr>
        <div class="row">
            <div class="col-8">
                <h2>{{ revenue.name }}</h2>
                <a href="{% url 'startups:revenues_update' revenue.id %}" type="button" class="btn btn-primary">Hisobotni tahrirlash</a>
                <a href="{% url 'startups:revenues_delete' revenue.id %}" type="button" class="btn btn-danger">Hisobotni o'chirish</a>
                
                <a href="{% url 'startups:revenues_fields_create' revenue.id %}" type="button" class="btn btn-primary">Soha Qo'shish</a>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Daromadlar (Mahsulot va xizmatlar bo'yicha)</th>
                            <th scope="col">Oylik hisobot uchun</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for field in revenue.get_fields %}
                            <tr>
                                <th scope="row">{{field.id}}</th>
                                <td>{{field.name}}</td>
                                <td>{{field.value}}</td>
                                <td> {{ field.date_created|timesince }} ago</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        {% endfor %}
{% endblock %}

templates/startups/admin.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    <h4>{{ page_title }}</h4>
{% endblock %}

{% block content %}
    <div class="container">
        <div>
            <div>
                <h4 class="p-2 m-2">{{startup.name}}</h4>
            </div>
            <a href="{% url 'startups:startup_update' startup.id %}" class="btn btn-primary">Tahrirlash</a>
            
        </div>
        <hr>
        <form action="{% url 'startups:revenues' startup.id %}" class="form-group" method="post">
            {% csrf_token %}
            {{ form|crispy}}
            <button class="btn btn-primary p-2 m-2" type="submit">Hisobot yaratish</button>
        </form>

        <table class="table table-striped">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Direktori</th>
                <th scope="col">Nomi</th>
                
                <th scope="col">Joriy Oydgi Daromad</th>
                <th scope="col">Joriy oydagi mijozlar soni</th>
                <th scope="col">Ish haqi</th>
                <th scope="col">Marketing reklama</th>
                
            </tr>
            </thead>

            <tbody>
                <tr>
                    <th scope="col">{{ startup.id}}</th>
                    <th scope="col">{{startup.created_by}}</th>
                    <th scope="col">{{startup.name}}</th>
                    
                    {% for revenue in startup.revenues%}
                        {% for field in revenue.get_fields() %}
                            <th scope="col">{{ field.name }}</th>
                        {% endfor %}
                    {% endfor %}
                    
                </tr>
            </tbody>
        <table>
        {% for startup in startups %}
        <hr>
        <div class="row">
            <div class="col-8">
                <h2>{{ startup.name }}</h2>
                <a href="{% url 'startups:revenues_update' revenue.id %}" type="button" class="btn btn-primary">Hisobotni tahrirlash</a>
                <a href="{% url 'startups:revenues_delete' revenue.id %}" type="button" class="btn btn-danger">Hisobotni o'chirish</a>
                
                <a href="{% url 'startups:revenues_fields_create' revenue.id %}" type="button" class="btn btn-primary">Soha Qo'shish</a>
                <table class="table table-striped">
                    <thead>
                        <tr>
                          <th scope="col">#</th>
                          <th scope="col">Direktori</th>
                          <th scope="col">Nomi</th>
                          
                          <th scope="col">Joriy Oydgi Daromad</th>
                          <th scope="col">Joriy oydagi mijozlar soni</th>
                          <th scope="col">Ish haqi</th>
                          <th scope="col">Marketing reklama</th>
                          
                        </tr>
                      </thead>
                    <tbody>
                        {% for field in revenue.get_fields %}
                            <tr>
                                <th scope="row">{{field.id}}</th>
                                <td>{{field.name}}</td>
                                <td>{{field.value}}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        {% endfor %}
{% endblock %}

templates/startups/delete_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    {{ page_title }}
{% endblock %}

{% block content %}
    <form method="post" class="m-4 p-4">
        <legend class="text-center">{{ page_title }}</legend>
        <fieldset class="form-group m-2 p-2">
            <span>Rostdan ham {{ object }} ni o;chirmoqchisimiz?</span>
            {% csrf_token %}
            {{ form|crispy }}
        </fieldset>
        <button type="submit" class="btn btn-danger">O'chirish</button>
        <a href="{% url 'startups:home' %}" class="btn btn-secondary"> Ortga </a>
    </form>
{% endblock %}

templates/startups/expense_add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
<h2>Xarajatlar</h2>
{% endblock %}

{% block content %}

       <div class="row">
        <div class="col-8">
            <h2>Xarajatlar</h2>
            <form method="post">
                {% csrf_token %}
              <div class="mb-3">
                <label for="id_salary" class="form-label">Ish haqi</label>
                <input type="text" class="form-control" id="id_salary" placeholder="Ish haqi" name="salary">
            </div>
            <div class="mb-3">
                <label for="id_marketing" class="form-label">Marketing reklama</label>
                <input type="text" class="form-control" id="id_marketing" placeholder="Marketing reklama" name="marketing">
            </div>
            <div class="mb-3">
                <button type="submit" class="btn btn-primary">Jo'natish</button>
            </div>

            </form>
        </div>
       </div>
      </div>
{% endblock %}

templates/startups/home.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    {{ page_title }}
{% endblock %}

{% block content %}
    <h2>Hisobotlar</h2>
    <a href="{% url 'startups:startup_create' %}" type="button" class="btn btn-primary">Qo'shish</a>
    <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">loyiha</th>
            <th scope="col">Vaqti</th>
          </tr>
        </thead>
        <tbody>
          {% for startup in object_list %}
          <tr>
            <th scope="row">{{ startup.id }}</th>
            <td><a href="{% url 'startups:reports' startup.id %}">{{ startup.name }}</a></td>
            <td>{{ startup.date_created }}</td>
            <td>
            {% if startup.author == request.user %}
                <a href="{% url 'startups:startup_update' startup.id %}" class="btn btn-primary"><i class="fa fa-pencil"></i></a>
                <a href="{% url 'startups:startup_delete' startup.id %}" class="btn btn-secondary"><i class="fa fa-trash"></i></a>
            {% endif %}
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
{% endblock %}

templates/startups/report_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    {{ page_title }}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-8">
            <h2>Daromad</h2>
            {% if request.user.is_superuser %}
            {% else %}
            <a href="{% url 'startups:revenue-add' startup.id %}" type="button" class="btn btn-primary">Qo'shish</a>
            {% endif %}
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Daromadlar (Mahsulot va xizmatlar bo'yicha)</th>
                        <th scope="col">Oylik hisobot uchun</th>
                    </tr>
                </thead>
                <tbody>
                    {% for revenue in object_list %}
                        <tr>
                            <th scope="row">{{ revenue.id }}</th>
                            <td>Joriy oyda olingan daromad</td>
                            <td>{{ revenue.income }}</td>

                            <td> {{ revenue.date_created }}</td>
                            {% if request.user.is_superuser %}
                                <td>{{ revenue.author }}</td>
                            {% endif %}
                        </tr>
                        <tr>
                            <th scope="row"></th>
                            <td>Joriy oydagi mijozlar soni</td>
                            <td>{{ revenue.clients }}</td>

                            <td> {{ revenue.date_created }}</td>
                            {% if request.user.is_superuser %}
                                <td>{{ revenue.author }}</td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-8">
            <h2>Xarajatlar</h2>
            {% if request.user.is_superuser %}
            {% else %}
            <a href="{% url 'startups:expense-add' startup.id %}" type="button" class="btn btn-primary">Qo'shish</a>
            {% endif %}
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Xarajatlar</th>
                        <th scope="col">Oylik hisobot uchun</th>
                    </tr>
                </thead>
                <tbody>
                    {% for outgoing in outgoings %}
                        <tr>
                            <th scope="row">{{ outgoing.id }}</th>
                            <td>Ish haqi</td>
                            <td>{{ outgoing.salary }}</td>
                            
                            <td> {{ outgoing.date_created }}</td>
                            {% if request.user.is_superuser %}
                                <td>{{ outgoing.author }}</td>
                            {% endif %}
                        </tr>
                        <tr>
                            <th scope="row"></th>
                            <td>Marketing reklama</td>
                            <td>{{ outgoing.marketing }}</td>

                            <td> {{ outgoing.date_created }}</td>
                            {% if request.user.is_superuser %}
                                <td>{{ outgoing.author }}</td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/startups/revenue_add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
<h2>Daromadlar</h2>
{% endblock %}

{% block content %}

<div class="row">
  <div class="col-8">
     
      <form method="post">
        {% csrf_token %}
        <div class="mb-3 form-group">
          <label for="id_income" class="form-label">Joriy oyda olingan daromad</label>
          <input type="text" class="form-control" id="id_income" placeholder="Joriy oyda olingan daromad" name="income">
        </div>
        <div class="mb-3 form-group">
            <label for="id_clients" class="form-label">Joriy oydagi mijozlar soni</label>
            <input type="text" class="form-control" id="id_clients" placeholder="Joriy oydagi mijozlar soni" name="clients">
        </div>
        <div class="mb-3 form-group">
            <button type="submit" class="btn btn-primary">Jo'natish</button>
        </div>
      </form>
  </div>
 </div>

 {% endblock %}