apps/startups/urls.py
from django.urls import path


from .views import (
    HomeView, startup_create, StartupUpdateView, StartupDeleteView,
    ReportListView, report_create, expense_create

)
app_name = "startups"
urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('startups/create/', startup_create, name="startup_create"),
    path('startups/<int:pk>/update/', StartupUpdateView.as_view(), name="startup_update"),
    path('startups/<int:pk>/delete/', StartupDeleteView.as_view(), name="startup_delete"),

    path('reports/<int:startup_id>/', ReportListView.as_view(), name="reports"),
    path('reports/<int:startup_id>/add-revenue/', report_create, name="revenue-add"),
    path('reports/<int:startup_id>/add-expense/', expense_create, name="expense-add"),
    
    
    path('admin/', HomeView.as_view(), name="admin")
]

apps/user/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from .views import SignUpView, LoginView

app_name = "user"
urlpatterns = [
    path('sign-up/', SignUpView.as_view(), name="signup"),
    path('sign-in/', LoginView.as_view(), name="login"),
    path('sign-out/', LogoutView.as_view(), name="logout"),
    
]

config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('djadmin/', admin.site.urls),
    path('', include("apps.user.urls")),
    path('', include("apps.startups.urls")),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>
        {% block title %}
            
        {% endblock %}
    </title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
</head>
<body>
    <header class="d-flex justify-content-between align-item-center">
        {% if request.user.is_superuser %}
        <a href="{% url 'startups:admin' %}" class="m-4 p-4">Logo</a>
        {% else %}
        <a href="{% url 'startups:home' %}" class="m-4 p-4">Logo</a>
        {% endif %}
        <div class="user m-4 p-4">
            {% if request.user.is_anonymous %}
                <a href="{% url 'user:signup' %}" class="btn btn-primary">Register</a>
                <a href="{% url 'user:login' %}" class="btn btn-primary">Login</a>
            {% else %}
                <a href="#" class="btn btn-primary">{{ request.user.fio }}</a>
                <a href="{% url 'user:logout' %}" class="btn btn-primary">Logout</a>
            {% endif %}
        </div>
    </header>

    <div class="container">

        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}

        {% block content%}
            
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js" integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous"></script>

</body>
</html>